Repository vektor-inc/vk-blocks-pro, pull requests merged in 2023-10, with the labels that each got.

#1819 【2人目確認待ち】Node.js を 18 に変更
  .eslintrc.js
  .husky/_/husky.sh
  .node-version
  babel.config.js
  jest.setup.js
  languages/vk-blocks-pro.pot
  package-lock.json
  package.json
  src/blocks/_pro/animation/transforms.js
  src/blocks/_pro/blog-card-excerpt/block.json
  src/blocks/_pro/blog-card-featured-image/block.json
  src/blocks/_pro/blog-card-site-logo/block.json
  src/blocks/_pro/blog-card-site-title/block.json
  src/blocks/_pro/blog-card-title/block.json
  src/blocks/_pro/blog-card/block.json
  src/blocks/_pro/blog-card/edit/index.js
  src/blocks/_pro/blog-card/utils.js
  src/blocks/_pro/breadcrumb/block.json
  src/blocks/_pro/dynamic-text/block.json
  src/blocks/_pro/grid-column-item/block.json
  src/blocks/_pro/gridcolcard-item-body/block.json
  src/blocks/_pro/gridcolcard-item-footer/block.json
  src/blocks/_pro/gridcolcard-item-header/block.json
  src/blocks/_pro/gridcolcard-item/block.json
  src/blocks/_pro/icon-card-item/block.json
  src/blocks/_pro/outer/component-divider.js
  src/blocks/_pro/post-list/block.json
  src/blocks/_pro/post-new-badge/block.json
  src/blocks/_pro/select-post-list-item/block.json
  src/blocks/bundle.js
  src/blocks/faq2-a/block.json
  src/blocks/faq2-q/block.json
  src/blocks/pr-blocks/block.json
  src/blocks/slider-item/block.json
  src/blocks/spacer/block.json
  src/blocks/staff/block.json
  src/extensions/core/group/style.js
  src/extensions/core/list/style.js
  test/e2e-tests/fixtures/blocks/vk-blocks__outer__default.html
  test/jest.config.js
Labels: 優先度：超高

#1834 【2人目確認待ち】[ 投稿リストブロック ] クエリを改変できるようにフック追加
  inc/vk-blocks/view/class-vk-blocks-postlist.php
  readme.txt
Labels: 優先度：超高, 確認待ち

#1831 設定画面の翻訳
  languages/vk-blocks-pro-ja-vk-blocks-admin-js.json
  languages/vk-blocks-pro-ja-vk-blocks-build-js.json
  languages/vk-blocks-pro-ja.po
Labels: 優先度：超高, 確認待ち

#1832 ブログカード スタイルシート 読み込みハンドル名修正
  src/blocks/_pro/blog-card-excerpt/index.php
  src/blocks/_pro/blog-card/index.php
Labels: 確認待ち

#1844 【2人目確認中】Swiper を 11.0.2 にアップデート
  composer.json
  composer.lock
  languages/vk-blocks-pro-ja-vk-blocks-admin-js.json
  languages/vk-blocks-pro-ja-vk-blocks-build-js.json
  languages/vk-blocks-pro-ja.mo
  languages/vk-blocks-pro-ja.po
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/slider/edit.js
Labels: 優先度：高, 確認待ち
