Repository vektor-inc/vk-blocks-pro, pull requests merged in 2023-06, with the labels that each got.

#1706 [ Bug fix ][ GridColCard ] Delete non intentional link underline
  readme.txt
  src/blocks/_pro/gridcolcard/style.scss
Labels: 確認待ち

#1728 Font Awesome オプション値の更新 API権限修正
  inc/vk-blocks/font-awesome/class-vk-blocks-font-awesome-api.php
  readme.txt
  src/utils/font-awesome-new.js
Labels: 優先度：超高

#1708 【確認待ち】無料版のデプロイを修正
  .eslintrc.js
  .freeignore
  .github/workflows/deploy-free.yml
  .github/workflows/develop-test.yml
  .gitignore
  .phpcs.xml
  .phpunit.xml
  bin/deploy-free.sh
  bin/install-theme.sh
  composer.json
  gulpfile.js
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  package-lock.json
  package.json
  phpunit.xml.dist
  src/blocks/staff/deprecated/0.58/component.js
  src/components/card-align-control/index.js
  test/phpunit/bootstrap.php
  test/phpunit/free/test-vk-block-is-pro.php
  test/phpunit/pro/test-custom-css-extension.php
  test/phpunit/pro/test-taxonomy.php
  vk-blocks.php
Labels: 優先度：超高

#1720 ライセンスキーの設定の表示・非表示の切り替えができるフィルターフックを追加
  inc/vk-blocks/admin/admin.php
  readme.txt
  test/phpunit/pro/test-license-check.php
  test/phpunit/pro/test-license-setting.php
  vk-blocks.php
Labels: 優先度：超高

#1747 【2人目確認待ち】[ ダイナミックテキスト ] 検索結果ページでのPHP Warning 修正
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/dynamic-text/index.php
Labels: bug
