Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-12, with the labels that each got.

#2361 投稿リストスライダーのスクリプトの呼び出し元を修正
  inc/vk-blocks-pro/vk-blocks-pro-functions.php
  inc/vk-blocks/vk-blocks-functions.php
  readme.txt
Labels: 優先度：高

#2322 [ カテゴリーバッジ ][ 不具合修正 ] バリエーションにタグが表示されてしまっていたので、表示されないように変更
  readme.txt
  src/blocks/_pro/post-category-badge/index.php
Labels: 優先度：高, 確認待ち

#2309 吹き出しブロックにデフォルト画像を設定
  inc/vk-blocks/images/avatar.png
  jest.setup.js
  readme.txt
  src/blocks/balloon/block.json
  src/blocks/balloon/deprecated/1.89.0/save.js
  src/blocks/balloon/deprecated/index.js
  src/blocks/balloon/edit.js
  src/blocks/balloon/index.php
  src/blocks/balloon/save.js
Labels: 確認待ち

#2369 【確認待ち】[ 吹き出し ] icon_displayをOFFにした時フロントエンドで80px分の空のスペースができてしまうので修正【1人でOK】
  src/blocks/balloon/style.scss
Labels: 優先度：超高

#2368 目次ブロックの改行を調整
  inc/vk-blocks/view/class-vk-blocks-postlist.php
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/post-list-slider/index.php
  src/blocks/_pro/table-of-contents-new/toc-utils.js
  src/blocks/balloon/style.scss
Labels: 優先度：高, 確認待ち

#2379 [ リスト / 枠線ボックス ]リストの is-style-default スタイルと枠線ボックスの色の処理を改善
  readme.txt
  src/blocks/border-box/style.scss
  src/utils/common.scss
Labels: 確認待ち

#2389 投稿リストスライダーが複数設置されたときに連動しないように
  readme.txt
  src/blocks/_pro/post-list-slider/block.json
  src/blocks/_pro/post-list-slider/edit.js
  src/blocks/_pro/post-list-slider/index.php
Labels: 優先度：中
