Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-07, with the labels that each got.

#2080 WordPress 6.6 RC1 で VK Blocks が使用できるように
  babel.config.js
  languages/vk-blocks-pro.po
  package-lock.json
  package.json
  readme.txt
  src/admin/index.js
  src/blocks/index.js
  webpack.config.js
Labels: 優先度：高

#2097 【確認中】[ リンクツールバー ] WP6.6で発生するエラーを修正
  readme.txt
  src/components/link-toolbar/index.js
Labels: 優先度：超高, 確認待ち

#2089 【2人め確認中】幅広のサイズをサポート
  editor-css/_editor_before_slider.scss
  languages/vk-blocks-pro-ja-vk-blocks-admin-js.json
  languages/vk-blocks-pro-ja-vk-blocks-build-js.json
  languages/vk-blocks-pro-ja.l10n.php
  languages/vk-blocks-pro-ja.mo
  languages/vk-blocks-pro-ja.po
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/grid-column-item/block.json
  src/blocks/_pro/grid-column-item/deprecated/1.78.0/save.js
  src/blocks/_pro/grid-column-item/deprecated/index.js
  src/blocks/_pro/grid-column-item/edit.js
  src/blocks/_pro/grid-column-item/save.js
  src/blocks/_pro/grid-column-item/style.scss
  src/blocks/_pro/table-of-contents-new/block.json
  src/blocks/_pro/table-of-contents-new/deprecated/1.78.0/save.js
  src/blocks/_pro/table-of-contents-new/deprecated/index.js
  src/blocks/_pro/table-of-contents-new/index.php
  src/blocks/_pro/table-of-contents-new/save.js
  src/blocks/_pro/table-of-contents-new/style.scss
  src/blocks/_pro/table-of-contents-new/view.js
  src/blocks/slider/edit.js
  src/components/link-toolbar/index.js
  test/e2e-tests/fixtures/blocks/vk-blocks__grid-column.html
  test/e2e-tests/fixtures/blocks/vk-blocks__grid-column__deprecated-1-78-0.html
  test/e2e-tests/fixtures/blocks/vk-blocks__table-of-contents-new.html
  test/e2e-tests/fixtures/blocks/vk-blocks__table-of-contents-new__deprecated-1-78-0.html
Labels: 確認待ち

#2108 【確認待ち】 [目次ブロック]jsでエラーが出ているのを修正
  src/blocks/_pro/table-of-contents-new/view.js
Labels: bug

#2107 ライセンスキーが正常の場合それを隠すように
  languages/vk-blocks-pro.pot
  package-lock.json
  readme.txt
  src/admin/license.js
Labels: 優先度：中

#2118 【2人目確認中】Node Scripts を更新
  .husky/_/husky.sh
  .husky/pre-commit
  .husky/pre-push
  languages/vk-blocks-pro.pot
  package-lock.json
  package.json
  src/components/advanced-color-gradient-control/index.js
Labels: 優先度：超高

#2125 WordPress 6.5.5 でもブロックが使えるように
  .husky/_/husky.sh
  .husky/pre-commit
  .husky/pre-push
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  package-lock.json
  package.json
  readme.txt
Labels: 優先度：超高

#2143 [ php微修正 / 1人でいいかも ] build-cssの読み込みを直しました
  inc/vk-blocks/class-vk-blocks-block-loader.php
Labels: 優先度：超高

#2144 [ 分割読み込み ] キーカラーが反映されない場合がある現象に対応しました
  readme.txt
  src/utils/common.scss
Labels: 優先度：高

#2142 VK Component を更新
  inc/vk-components/package/class-vk-component-posts.php
  inc/vk-components/package/css/vk-components.css
  readme.txt
Labels: 優先度：中, 確認待ち

#2147 [ 投稿リスト ] 2ページ目以降の投稿表示を修正しました
  inc/vk-blocks/view/class-vk-blocks-postlist.php
  readme.txt
Labels: 優先度：高
