Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-02, with the labels that each got.

#1908 【確認待ち（一人でいいかな）】２ページ以降でも１ページにロックする設定を追加
  inc/vk-blocks/view/class-vk-blocks-postlist.php
  inc/vk-components/package/class-vk-component-posts.php
  languages/vk-blocks-pro-ja-vk-blocks-admin-js.json
  languages/vk-blocks-pro-ja-vk-blocks-build-js.json
  languages/vk-blocks-pro-ja.mo
  languages/vk-blocks-pro-ja.po
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/post-list/block.json
  src/blocks/_pro/post-list/edit.js
  src/blocks/_pro/post-list/index.php
  test/phpunit/pro/test-post-list-query.php
Labels: お知らせ記事待ち

#1891 【二人目確認待ち】スライダーの縦積みモードとスライドモードの切り替えを追加
  editor-css/_editor_before_slider.scss
  gulpfile.js
  languages/vk-blocks-pro-ja-vk-blocks-admin-js.json
  languages/vk-blocks-pro-ja-vk-blocks-build-js.json
  languages/vk-blocks-pro-ja.mo
  languages/vk-blocks-pro-ja.po
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/slider-item/edit.js
  src/blocks/slider/block.json
  src/blocks/slider/deprecated/save/index.js
  src/blocks/slider/edit.js
  src/blocks/slider/editor-script.js
  src/blocks/slider/index.php
  src/blocks/slider/style.scss
Labels: 優先度：中, 確認待ち

#1917 【確認中】編集スライダーをサイトエディタ / ウィジェットエディタに対応
  .eslintrc.js
  gulpfile.js
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  package-lock.json
  package.json
  readme.txt
  src/blocks/slider-item/edit.js
  src/blocks/slider/edit.js
  src/blocks/slider/editor-script.js
  src/blocks/slider/index.php
  test/jest.config.js
Labels: 優先度：超高, 確認待ち

#1925 【確認待ち】[ スライダー ] 中の要素が編集できなくなる不具合を修正
  readme.txt
  src/blocks/slider-item/style.scss
Labels: 優先度：超高

#1915 【確認待ち】[ グリッドカラムカード ] カードブロック内の上下要素の指定が編集画面で効かない（下揃えになってしまう）不具合を修正
  editor-css/_editor_before_gridcolcard.scss
  readme.txt
Labels: 優先度：超高
