Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-04, with the labels that each got.

#1941 【2人目確認待ち】アコーディオンブロックに「装飾なし」スタイルを追加
  readme.txt
  src/blocks/_pro/accordion/index.js
  src/blocks/_pro/accordion/style.scss
Labels: 確認待ち

#1958 6.5で目次のタイトルが表示されない不具合修正
  readme.txt
  src/blocks/_pro/table-of-contents-new/toc-utils.js
Labels: 優先度：超高

#1969 【2人目確認中】グループブロックのスタイルstitch で、内部のリンクが効かなくなるのを修正
  readme.txt
  src/utils/common.scss
Labels: 確認待ち

#1977 【2人目確認待ち】[ グリッドカラム ] アイテムを先頭寄せに変更 & 親要素の基本幅を保つように修正しました。
  readme.txt
  src/blocks/_pro/grid-column/style.scss
Labels: 確認待ち

#1976 WordPress 6.5 の翻訳システムに対応
  .phpcs.xml
  languages/vk-blocks-pro-ja.l10n.php
  languages/vk-blocks-pro.l10n.php
  languages/vk-blocks-pro.pot
  package.json
  readme.txt
Labels: 優先度：超高

#1979 WordPress 6.5 で useSetting が非推奨になったので変更
  package-lock.json
  package.json
  readme.txt
  src/blocks/_pro/blog-card-featured-image/dimension-controls.js
  src/components/advanced-color-gradient-control/index.js
Labels: 優先度：超高, 確認待ち

#1973 WordPress 6.5 環境で発生するコンソールエラーの修正
  readme.txt
  src/blocks/_pro/accordion/block.json
  src/blocks/_pro/accordion/index.php
  src/blocks/_pro/animation/block.json
  src/blocks/_pro/animation/index.php
  src/blocks/faq/block.json
  src/blocks/faq/index.php
  src/blocks/faq2/block.json
  src/blocks/faq2/index.php
Labels: 優先度：超高
