Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-11, with the labels that each got.

#2293 [ 分割読み込み ] x-t9 のとき画像、テーブル、見出しのスタイルが反映されないのを修正
  inc/vk-blocks/class-vk-blocks-block-loader.php
  readme.txt
  test/phpunit/pro/test-block-loader.php
Labels: 優先度：高

#2299 分割読み込みがOFF(→ではなくでONかつ編集画面)かつdevelopブランチの時: VK Blocks のレスポンシブスペーサーを設置すると高さがでないのを修正
  inc/vk-blocks/class-vk-blocks-block-loader.php
Labels: 優先度：超高

#2294 [ 目次 ] 初期表示状態CLOSE時、フロント画面でOPENボタンをクリックすると1回目のみCLOSE表記にならない現象を修正
  readme.txt
  src/blocks/_pro/table-of-contents-new/style.scss
  src/blocks/_pro/table-of-contents-new/view.js
Labels: 優先度：高

#2314 【確認待ち】GithubのActionで必ずPlaywright Testsが引っ掛かってしまうのを修正していただきました
  test/e2e/heading-transform.spec.ts
Labels: 優先度：超高

#2316 [ WP6.7 ] 日本語の翻訳が効いていなかったのを修正しました（リフレッシュ） #2311
  inc/vk-blocks/vk-blocks-functions.php
  readme.txt
  vk-blocks.php
Labels: 優先度：超高

#2330 [ CSS微修正 ] グリッドカラムカードアイテム内で区切りのドット以外が表示されないのを修正しました
  readme.txt
  src/blocks/_pro/gridcolcard/style.scss
Labels: 優先度：中

#2286 スライダーブロックの編集画面をリファクタリング
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/slider/edit-multiItem.js
  src/blocks/slider/edit-slider.js
  src/blocks/slider/edit.js
Labels: 優先度：低, 確認待ち

#2337 タクソノミーブロックの表示を日本語表記にしてほしい（All of の翻訳を修正）
  languages/vk-blocks-pro-ja-vk-blocks-admin-js.json
  languages/vk-blocks-pro-ja-vk-blocks-build-js.json
  languages/vk-blocks-pro-ja.l10n.php
  languages/vk-blocks-pro-ja.mo
  languages/vk-blocks-pro-ja.po
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
Labels: 優先度：高

#2342 [ 投稿リストスライダー ] 背景設定を削除
  languages/vk-blocks-pro-ja.l10n.php
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.l10n.php
  languages/vk-blocks-pro.pot
  src/blocks/_pro/post-list-slider/block.json
  src/blocks/_pro/post-list-slider/edit.js
  src/blocks/_pro/post-list-slider/index.php
  src/blocks/_pro/post-list-slider/style.scss
  test/phpunit/pro/test-post-list-slider.php
Labels: 優先度：超高, 確認待ち

#2341 [ 固定表示 ] タイマー設定に関する不具合を修正しました
  src/blocks/_pro/fixed-display/edit.js
  src/blocks/_pro/fixed-display/save.js
  src/blocks/_pro/fixed-display/view.js
Labels: 優先度：超高
