Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-05, with the labels that each got.

#1991 [ 共通余白設定 ] Vk Block Settingに 2xs と 2xl を追加
  inc/vk-blocks/class-vk-blocks-options.php
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/admin/margin.js
  src/blocks/spacer/edit.js
Labels: 優先度：高

#1189 タブブロック追加
  editor-css/_editor_before.scss
  editor-css/_editor_before_tab.scss
  gulpfile.js
  inc/vk-blocks-pro/vk-blocks-pro-functions.php
  inc/vk-blocks/class-vk-blocks-global-settings.php
  inc/vk-blocks/languages/vk-blocks-js.pot
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.l10n.php
  languages/vk-blocks-pro.po
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/tab-item/block.json
  src/blocks/_pro/tab-item/edit.js
  src/blocks/_pro/tab-item/icon.svg
  src/blocks/_pro/tab-item/index.js
  src/blocks/_pro/tab-item/index.php
  src/blocks/_pro/tab-item/save.js
  src/blocks/_pro/tab/block.json
  src/blocks/_pro/tab/edit.js
  src/blocks/_pro/tab/icon.svg
  src/blocks/_pro/tab/index.js
  src/blocks/_pro/tab/index.php
  src/blocks/_pro/tab/save.js
  src/blocks/_pro/tab/style.scss
  src/blocks/_pro/tab/view.js
  src/blocks/bundle-pro.js
  src/components/advanced-color-palette/index.js
  test/e2e-tests/fixtures/blocks/vk-blocks__tab__default.html
  test/integration/full-content/full-content.test.js
Labels: 優先度：中

#2015 【確認待ち(1人確認でOK)】[ タブ ] アイコン選択パネルで Pro のラベルを追加
  editor-css/_editor_before.scss
Labels: 確認待ち

#2022 [ ボタン ] 編集画面でリンクがクリックできてしまう現象を修正しました
  readme.txt
  src/blocks/button/edit.js
Labels: 優先度：超高
