Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-10, with the labels that each got.

#2245 分割読み込みが OFF でも分割読み込み用のスタイルが読み込まれていないことを修正
  readme.txt
  src/blocks/_pro/accordion/block.json
  src/blocks/_pro/animation/block.json
  src/blocks/_pro/fixed-display/block.json
  src/blocks/_pro/tab-item/block.json
  src/blocks/_pro/tab/block.json
  src/blocks/_pro/table-of-contents-new/block.json
  src/blocks/faq/block.json
  src/blocks/faq2/block.json
  src/blocks/slider/block.json
  src/blocks/slider/index.php
Labels: 優先度：高

#2231 [ core/table ] 特定の条件の時にスクロールモードにすると完全に解除できないのを修正しました
  readme.txt
  src/extensions/core/table/style.js
Labels: 優先度：高

#2250 [ リンクツールバー ] 編集画面でのCORSエラーを回避するように修正しました
  readme.txt
  src/components/link-toolbar/index.js
Labels: 優先度：中

#2244 【2人目確認中】[ core/heading, core/image, core/table ] 分割読み込み無効時に個別のコアブロックのCSSが読み込まれる問題を修正
  inc/vk-blocks/class-vk-blocks-block-loader.php
Labels: 優先度：高

#2252 [ 固定表示 ] 固定位置が上・下の時に上部(下部)からの固定位置のクラス名がついてしまうのを修正しました
  src/blocks/_pro/fixed-display/edit.js
  src/blocks/_pro/fixed-display/save.js
  test/e2e-tests/fixtures/blocks/vk-blocks__fixed-display__default.html
  test/e2e-tests/fixtures/blocks/vk-blocks__fixed-display__deprecated-1-81-1.html
Labels: 優先度：超高

#2261 swiper を読み込むタイミングを調整することでスライダーが崩れないように
  inc/vk-blocks/class-vk-blocks-block-loader.php
  readme.txt
  src/blocks/slider/block.json
  src/components/link-toolbar/index.js
Labels: 優先度：超高, 確認待ち

#2267 リンクコンポーネントで tel: と mailto: リンクの不具合を修正
  readme.txt
  src/components/link-toolbar/index.js
Labels: 確認待ち

#2271 [ Bug fix ][ Slider ] Fix an issue where full width alignment does not work in tt4 and tt5.
  readme.txt
  src/blocks/slider/style.scss
Labels: 優先度：中

#2278 [ Core/group ] 横並び、縦積み、グリッド表示時にリンクあり/なしの状態で並び方が異なっているのを修正
  readme.txt
  src/extensions/core/group/style.js
Labels: 優先度：超高

#554 アコーディオンブロックを編集画面で開閉できるように
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/accordion-trigger/edit.js
  src/blocks/_pro/accordion/style.scss
Labels: 優先度：低
