Repository vektor-inc/vk-blocks-pro, pull requests merged in 2024-06, with the labels that each got.

#2024 VK ブロックを最上位に
  inc/vk-blocks/blocks.php
  readme.txt
  src/block-category/index.js
  src/blocks/index.js
Labels: 優先度：中

#2032 [ 固定表示ブロック ] 編集画面で固定位置「右」「左」の時の位置関係の修正
  gulpfile.js
  languages/vk-blocks-pro-ja-vk-blocks-admin-js.json
  languages/vk-blocks-pro-ja-vk-blocks-build-js.json
  languages/vk-blocks-pro-ja.l10n.php
  languages/vk-blocks-pro-ja.mo
  languages/vk-blocks-pro-ja.po
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/fixed-display/edit.js
  src/blocks/_pro/fixed-display/view.js
Labels: 優先度：高

#2031 VK Blocks が有効な状態で VK Blocks Pro を有効化してもエラーにならないように
  .eslintrc.js
  .github/workflows/develop-test.yml
  .gitignore
  readme.txt
  test/phpunit/bootstrap.php
  vk-blocks.php
Labels: 優先度：超高, 確認待ち

#2040 【確認待ち】[readme]Description にカラムの逆方向を追加
  readme.txt
Labels: 優先度：低, 確認待ち

#2051 【2人目確認中】ブロック挿入画面において VK Blocks系のブロックの挿入位置を変更する設定を追加
  inc/vk-blocks/blocks.php
  inc/vk-blocks/class-vk-blocks-options.php
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.pot
  readme.txt
  src/admin/block-category-position.js
  src/admin/index.js
  test/phpunit/pro/test-get-options.php
Labels: 優先度：超高

#2055 【2人目確認待ち】[ タブ ] アクティブなタブをクリックするとタブの背景色がなくなる現象に対応しました
  readme.txt
  src/blocks/_pro/tab/view.js
Labels: 優先度：超高

#1998 【確認中】[ 枠線ボックス ] 0系統のdeprecatedを削除
  src/blocks/border-box/deprecated/0.0.0/save.js
  src/blocks/border-box/deprecated/0.0.1/save.js
  src/blocks/border-box/deprecated/index.js
  test/e2e-tests/fixtures/blocks/vk-blocks__border-box__deprecated-0-60-1.html
Labels: 優先度：超低

#1996 [ PR Blocks ] 0系統のdeprecatedを削除
  src/blocks/pr-blocks/deprecated/0.0.0/save.js
  src/blocks/pr-blocks/deprecated/0.0.0/schema.js
  src/blocks/pr-blocks/deprecated/0.0.1/component.js
  src/blocks/pr-blocks/deprecated/0.0.1/save.js
  src/blocks/pr-blocks/deprecated/0.0.1/schema.js
  src/blocks/pr-blocks/deprecated/0.0.2/component.js
  src/blocks/pr-blocks/deprecated/0.0.2/save.js
  src/blocks/pr-blocks/deprecated/0.0.2/schema.js
  src/blocks/pr-blocks/deprecated/0.59.0/component.js
  src/blocks/pr-blocks/deprecated/0.59.0/save.js
  src/blocks/pr-blocks/deprecated/0.59.0/schema.js
  src/blocks/pr-blocks/deprecated/index.js
  test/e2e-tests/fixtures/blocks/vk-blocks__pr-blocks__default.html
  test/e2e-tests/fixtures/blocks/vk-blocks__pr-blocks__deprecated-0-60-1.html
Labels: 優先度：超低

#2074 Delete unnecessary development files included in 1.76.2.
  package.json
  readme.txt
Labels: 優先度：高
