Repository vektor-inc/vk-blocks-pro, pull requests merged in 2025-03, with the labels that each got.

#2466 【確認中】GitHub Actionsの actions/XXX@v2 廃止に伴う修正 (@v4 に更新)
  .github/workflows/ci-test-lint-deprecated.yml
  .github/workflows/deploy-free.yml
  .github/workflows/develop-test.yml
  .github/workflows/playwright.yml
  .github/workflows/release-github-and-deploy-test-sv.yml
  .github/workflows/release-vws.yml
Labels: 優先度：超高

#2498 [ 不具合修正 ][ フロー ] フロントエンドでの画像のはみ出しとエディター内の矢印のずれを修正
  readme.txt
  src/blocks/flow/style.scss
Labels: 確認待ち

#2496 [ 不具合修正 ][ ブログカード ] 'clearCache' キー欠落によるPHP 8.xの警告を修正
  readme.txt
  src/blocks/_pro/blog-card/api/fetch-url-data.js
Labels: 優先度：中

#2506 [ ダイナミックテキスト ][ 機能追加 ] 表示要素に投稿スラッグを追加
  readme.txt
  src/blocks/_pro/dynamic-text/block.json
  src/blocks/_pro/dynamic-text/edit.js
  src/blocks/_pro/dynamic-text/index.php
  test/phpunit/pro/test-dynamic-text.php
Labels: 優先度：超高
