Repository vektor-inc/vk-blocks-pro, pull requests merged in 2025-04, with the labels that each got.

#2511 [ 不具合修正 ][ グループ ] layout が未定義・不正なテーマで編集画面が白くならないように修正
  readme.txt
  src/extensions/core/group/style.js
Labels: bug, 優先度：高

#2505 [ 機能追加 ][ ダイナミックテキスト ] カスタムフィールドの表示でリンクURLに設定した場合はリンクテキストを指定する機能を追加
  readme.txt
  src/blocks/_pro/dynamic-text/block.json
  src/blocks/_pro/dynamic-text/edit.js
  src/blocks/_pro/dynamic-text/index.php
Labels: 優先度：高

#2523 [ その他 ] hook.js の未使用の関数を削除
  src/utils/hooks.js
Labels: 優先度：高, 確認待ち

#2526 Github Actionsでプルリクアップ時にwp-env startの所でエラーになることが増えたためリトライロジック追加
  .github/workflows/ci-test-lint-deprecated.yml
  .github/workflows/develop-test.yml
Labels: enhancement, 優先度：高

#2525 [ ダイナミックテキスト ] 編集画面では投稿のリンクをクリックしても飛ばないようにしました
  readme.txt
  src/blocks/_pro/dynamic-text/edit.js
Labels: 優先度：中, 確認待ち

#2521 【2人目確中】[ その他 ] asyncHooks.js を廃止
  readme.txt
  src/blocks/_pro/step/edit.js
  src/utils/asyncHooks.js
Labels: 優先度：高, 確認待ち

#2528 【二人目確認中】[ 目次ブロック ] パフォーマンスと信頼性を改善
  readme.txt
  src/blocks/_pro/table-of-contents-new/edit.js
  src/utils/hooks.js
Labels: 優先度：高, 確認待ち

#2519 [ その他 ][ 6.8対応 ] BoxControl を 6.6 ～ 6.8 準拠に対応
  readme.txt
  src/blocks/_pro/gridcolcard/edit-common.js
Labels: 優先度：高, 確認待ち

#2531 [ 不具合修正 ][ フロー ] ブロック選択時に選択状態がわからなくなる問題を修正（編集画面でフローブロックの矢印がCSSではなくHTMLで出力されるように変更）
  readme.txt
  src/blocks/flow/edit.js
  src/blocks/flow/style.scss
Labels: 優先度：超高

#2520 [ その他 ][ 6.8対応 ][ タブ ] useSelectフックに依存配列を追加しました
  src/blocks/_pro/tab/edit.js
Labels: 優先度：高

#2535 【二人目確認待ち】[ 不具合修正 ][ ステップ ] ステップの開始番号が空欄の場合の処理を変更
  readme.txt
  src/blocks/_pro/step/edit.js
Labels: 優先度：高, 確認待ち

#2551 [ 不具合修正 ] 有料版を有効化したら無料版を無効化するように再調整
  .github/workflows/develop-test.yml
  readme.txt
  test/phpunit/pro/test-activate.php
  vk-blocks.php
Labels: 優先度：中, 確認待ち

#2473 【2人目確認中】[ 不具合修正 ][ Outer ] 区切りの上下に意図しない線が出る不具合を修正
  editor-css/_editor_after_admin_sidebar.scss
  readme.txt
  src/blocks/_pro/outer/style.scss
Labels: 優先度：超高

#2572 GitHub Actions上のPlaywrightインストールから--with-depsを除去（プルリクアップ時のエラー回避）
  .github/workflows/playwright.yml
Labels: 優先度：超高

#2573 【二人目確認中】[ デザイン不具合修正 ][ Outer ] 区切りの左右に意図しない線が出る不具合を修正
  readme.txt
  src/blocks/_pro/outer/style.scss
Labels: 優先度：高
