Repository vektor-inc/vk-blocks-pro, pull requests merged in 2025-02, with the labels that each got.

#2447 ベクトル製以外のテーマでは 編集画面の挙動がおかしいブロックがあるのを修正
  inc/vk-blocks/load-vk-components.php
  src/blocks/_pro/post-list-slider/edit.js
  src/blocks/_pro/post-list/edit.js
  src/blocks/_pro/tab/edit.js
  src/blocks/_pro/table-of-contents-new/style.scss
  src/blocks/slider/edit-slider.js
Labels: 優先度：超高

#2455 タブブロック (.vk_tab) 内のブロック挿入ボタン (block-list-appender) が他のブロック挿入ボタンに影響を与える問題を修正しました。
  editor-css/_editor_before_tab.scss
  readme.txt
Labels: 確認待ち

#2458 [ 投稿リスト / 投稿リストスライダー / タブ /スライダー ] 編集画面の環境がiframeであるかないか関わらずエラーが出たり機能が安定して動作するよう修正
  readme.txt
  src/blocks/_pro/post-list-slider/edit.js
  src/blocks/_pro/post-list/edit.js
  src/blocks/_pro/tab/edit.js
  src/blocks/slider/edit-slider.js
  src/blocks/slider/edit.js
Labels: 優先度：超高

#2460 [ 投稿リスト / 投稿リストスライダー ] 投稿がない時のテキストを修正しました（'s' 表記を削除&最初の文字を小文字に統一しました）
  inc/vk-blocks/view/class-vk-blocks-postlist.php
  readme.txt
Labels: 優先度：高

#2453 カラムブロック拡張のリファクタリング
  src/extensions/core/columns/style.js
Labels: 優先度：中, 確認待ち
