Repository vektor-inc/vk-blocks-pro, pull requests merged in 2025-01, with the labels that each got.

#2392 block.js から vk-blocks-build-css の記述を削除
  languages/vk-blocks-pro-ja.l10n.php
  languages/vk-blocks-pro-js.pot
  languages/vk-blocks-pro.l10n.php
  languages/vk-blocks-pro.pot
  readme.txt
  src/blocks/_pro/accordion/block.json
  src/blocks/_pro/animation/block.json
  src/blocks/_pro/fixed-display/block.json
  src/blocks/_pro/post-list-slider/block.json
  src/blocks/_pro/tab-item/block.json
  src/blocks/_pro/tab/block.json
  src/blocks/_pro/table-of-contents-new/block.json
  src/blocks/faq/block.json
  src/blocks/faq2/block.json
  src/blocks/slider/block.json
Labels: 優先度：超高

#2363 VK Compo を Composer から取得
  composer.json
  composer.lock
  gulpfile.js
  inc/vk-blocks-config.php
  inc/vk-blocks/load-vk-components.php
  inc/vk-blocks/view/class-vk-blocks-postlist.php
  inc/vk-component/config.php
  inc/vk-components/package/_scss/_vk-post-type-card.scss
  inc/vk-components/package/_scss/_vk-post-type-media.scss
  inc/vk-components/package/_scss/_vk-post-type-text.scss
  inc/vk-components/package/_scss/_vk-post.scss
  inc/vk-components/package/_scss/vk-components.scss
  inc/vk-components/package/class-vk-component-button.php
  inc/vk-components/package/class-vk-component-mini-contents.php
  inc/vk-components/package/class-vk-component-posts.php
  inc/vk-components/package/css/vk-components.css
  inc/vk-components/vk-components-config.php
  languages/vk-blocks-pro-js.pot
  package.json
  readme.txt
  src/blocks/_pro/post-list-slider/index.php
  src/blocks/_pro/select-post-list-item/index.php
Labels: 優先度：中, 確認待ち

#2407 [ visual embed ] iframeのmargin-bottomを0にしました
  src/blocks/visual-embed/style.scss
Labels: 確認待ち

#2414 [ ビジュアル埋め込み ] XSS対策のためのバリデーション強化並びに許可されるURLの範囲の制限を追加
  readme.txt
  src/blocks/visual-embed/edit.js
  src/blocks/visual-embed/index.php
  src/blocks/visual-embed/style.scss
Labels: 優先度：超高

#2410 [ テーブル ] 縦積み機能を追加
  readme.txt
  src/extensions/core/table/style.js
  src/extensions/core/table/style.scss
Labels: 優先度：中

#2431 [ responsive br ] commitエラーを引き起こすためラベルを修正
  src/extensions/common/responsive-br/index.js
Labels: 優先度：超高

#2435 playwrightのテストが通らなくなってたので update-artifactを v4 に更新しました
  .github/workflows/playwright.yml
Labels: 優先度：超高

#2424 [ Page Content / 固定ページ本文 ] 非公開の固定ページは表示しないように仕様変更
  readme.txt
  src/blocks/page-content/class-vk-blocks-check-using-vk-page-content-block.php
  src/blocks/page-content/edit.js
  src/blocks/page-content/index.php
  test/phpunit/free/test-page-content.php
  test/phpunit/free/test-vk-blocks-check-using-vk-page-content-block.php
  vk-blocks.php
Labels: 優先度：高
